name: notebook
channels:
  - conda-forge
dependencies:
  - python=3.12

  # Jupyter environment
  - jupyterlab
  - notebook
  - ipywidgets
  - ipykernel
  - ipython

  # Visualization
  - matplotlib
  - bokeh

  - pip
  - pip:
      - climakitae
